#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class RowDefinition;
                ref class Button;
                ref class TextBlock;
                ref class TextBox;
            }
        }
    }
}

namespace CoaxialCalculator
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::RowDefinition^ RowDefinitionHeader;
        private: ::Windows::UI::Xaml::Controls::Button^ ButtonStart;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_Pmax;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_Umax;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_rho;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_alpha_sum;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_alpha_m;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_alpha_d;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_zct;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_vfl;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ TextBlock_lambda;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_tanDelta;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_ep;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_epsilon;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_sigma;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_F;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_D;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBox_d;
    };
}

